version: '2'
services:
  photobook-kaimook:
    container_name: photobook-kaimook
    image: photobook-kaimook:latest
    mem_limit: 2000m
    restart: always
    build:
      context: .
    ports:
      - "3002:5000"
    network_mode: bridge